<?php

declare(strict_types=1);

// Cross-probe mission-history timeline for the /milestones page. Static, hand-transcribed
// facts like config/probes.php -- no live source for mission history. Sourced from NASA/JPL
// primary announcements (jpl.nasa.gov, science.nasa.gov); dates verified 2026-08-21. Newest
// first -- keep new entries in that order, since the /milestones route's sort is a safety net,
// not something to rely on.

return [
    [
        'date' => '2026-08-04',
        'dateLabel' => 'Aug 4, 2026',
        'probe' => 'voyager-2',
        'icon' => 'lightning',
        'title' => "'Big Bang' power swap buys a year",
        'body' => "A one-shot, no-margin-for-error power-system swap frees enough electricity to keep Voyager 2's three remaining instruments running at least another year.",
    ],
    [
        'date' => '2026-04-17',
        'dateLabel' => 'Apr 17, 2026',
        'probe' => 'voyager-1',
        'icon' => 'power',
        'title' => 'Last charged-particle instrument goes dark',
        'body' => 'Following an unexpected power drop during a roll maneuver, NASA shuts off the low-energy charged particles instrument after nearly 49 years of continuous operation.',
    ],
    [
        'date' => '2025-03-24',
        'dateLabel' => 'Mar 24, 2025',
        'probe' => 'voyager-2',
        'icon' => 'power',
        'title' => 'Low-energy particle instrument powered down',
        'body' => "Voyager 2's low-energy particle instrument is switched off the same week as Voyager 1's cosmic ray subsystem, part of a coordinated plan to stretch the mission's dwindling plutonium power.",
    ],
    [
        'date' => '2025-03-20',
        'dateLabel' => 'Mar 20, 2025',
        'probe' => 'voyager-1',
        'icon' => 'gear',
        'title' => 'Revives thrusters dormant since 2004',
        'body' => "Engineers successfully test-fire Voyager 1's long-idle primary roll thrusters, restoring a working backup ahead of a months-long Deep Space Network antenna outage.",
    ],
    [
        'date' => '2025-02-25',
        'dateLabel' => 'Feb 25, 2025',
        'probe' => 'voyager-1',
        'icon' => 'power',
        'title' => 'Cosmic ray instrument powered down',
        'body' => "NASA shuts off Voyager 1's cosmic ray subsystem to conserve fading power, part of the same coordinated shutdown plan as Voyager 2's low-energy particle instrument.",
    ],
    [
        'date' => '2024-09-26',
        'dateLabel' => 'Sep 26, 2024',
        'probe' => 'voyager-2',
        'icon' => 'power',
        'title' => 'Plasma instrument powered down',
        'body' => "NASA deactivates Voyager 2's Plasma Science Experiment to conserve fading power, leaving three active instruments.",
    ],
    [
        'date' => '2024-08-27',
        'dateLabel' => 'Aug 27, 2024',
        'probe' => 'voyager-1',
        'icon' => 'gear',
        'title' => 'Switches to backup attitude thrusters',
        'body' => "Silicon-dioxide buildup clogs Voyager 1's trajectory-correction fuel line to half a human hair's width, forcing a switch to its attitude-propulsion thrusters to stay pointed at Earth.",
    ],
    [
        'date' => '2024-04-22',
        'dateLabel' => 'Apr 22, 2024',
        'probe' => 'voyager-1',
        'icon' => 'check-circle',
        'title' => 'Speaks clearly again',
        'body' => 'A software patch works around corrupted memory hardware, and Voyager 1 resumes sending readable engineering data.',
    ],
    [
        'date' => '2023-11-14',
        'dateLabel' => 'Nov 14, 2023',
        'probe' => 'voyager-1',
        'icon' => 'warning',
        'title' => 'Sends unreadable data',
        'body' => 'The flight data system begins transmitting garbled telemetry after a memory chip fails; engineers work the problem for five months.',
    ],
    [
        'date' => '2023-08-04',
        'dateLabel' => 'Aug 4, 2023',
        'probe' => 'voyager-2',
        'icon' => 'check-circle',
        'title' => 'Contact restored',
        'body' => "The Deep Space Network's most powerful transmitter sends an \"interstellar shout\" that reaches the probe and re-points its antenna at Earth.",
    ],
    [
        'date' => '2023-07-21',
        'dateLabel' => 'Jul 21, 2023',
        'probe' => 'voyager-2',
        'icon' => 'warning',
        'title' => 'Signal lost',
        'body' => 'A routine command accidentally tilts the antenna two degrees off Earth, cutting off contact.',
    ],
    [
        'date' => '2018-11-05',
        'dateLabel' => 'Nov 5, 2018',
        'probe' => 'voyager-2',
        'icon' => 'arrow-line-up-right',
        'title' => 'Crosses the heliopause',
        'body' => 'Voyager 2 exits the heliosphere and becomes the second human-made object in interstellar space.',
    ],
    [
        'date' => '2012-08-25',
        'dateLabel' => 'Aug 25, 2012',
        'probe' => 'voyager-1',
        'icon' => 'arrow-line-up-right',
        'title' => 'Crosses the heliopause',
        'body' => 'Voyager 1 becomes the first spacecraft to leave the heliosphere and enter interstellar space.',
    ],
    [
        'date' => '1990-02-14',
        'dateLabel' => 'Feb 14, 1990',
        'probe' => 'voyager-1',
        'icon' => 'camera',
        'title' => "The 'Pale Blue Dot'",
        'body' => 'Cameras turn back for a final family portrait of the Solar System, then power down for good to save energy.',
    ],
    [
        'date' => '1989-08-25',
        'dateLabel' => 'Aug 25, 1989',
        'probe' => 'voyager-2',
        'icon' => 'planet',
        'title' => 'Neptune flyby',
        'body' => 'Closest approach to Neptune — the final planetary encounter of the Grand Tour, and the only spacecraft ever to visit.',
    ],
    [
        'date' => '1986-01-24',
        'dateLabel' => 'Jan 24, 1986',
        'probe' => 'voyager-2',
        'icon' => 'planet',
        'title' => 'Uranus flyby',
        'body' => 'Closest approach to Uranus, discovering ten new moons and a sharper picture of its tilted magnetic field.',
    ],
    [
        'date' => '1981-08-25',
        'dateLabel' => 'Aug 25, 1981',
        'probe' => 'voyager-2',
        'icon' => 'planet',
        'title' => 'Saturn flyby',
        'body' => 'Closest approach to Saturn, imaging its rings and moons in detail.',
    ],
    [
        'date' => '1980-11-12',
        'dateLabel' => 'Nov 12, 1980',
        'probe' => 'voyager-1',
        'icon' => 'planet',
        'title' => 'Saturn flyby',
        'body' => 'Closest approach to Saturn, returning the first close images of its ring structure.',
    ],
    [
        'date' => '1979-07-09',
        'dateLabel' => 'Jul 9, 1979',
        'probe' => 'voyager-2',
        'icon' => 'planet',
        'title' => 'Jupiter flyby',
        'body' => 'Closest approach to Jupiter, capturing the first clear images of its faint ring system.',
    ],
    [
        'date' => '1979-03-05',
        'dateLabel' => 'Mar 5, 1979',
        'probe' => 'voyager-1',
        'icon' => 'planet',
        'title' => 'Jupiter flyby',
        'body' => 'Closest approach to Jupiter, discovering active volcanoes on the moon Io.',
    ],
    [
        'date' => '1977-09-05',
        'dateLabel' => 'Sep 5, 1977',
        'probe' => 'voyager-1',
        'icon' => 'rocket-launch',
        'title' => 'Launch',
        'body' => 'Lifts off from Cape Canaveral aboard a Titan-Centaur rocket, carrying the Golden Record.',
    ],
    [
        'date' => '1977-08-20',
        'dateLabel' => 'Aug 20, 1977',
        'probe' => 'voyager-2',
        'icon' => 'rocket-launch',
        'title' => 'Launch',
        'body' => 'Lifts off from Cape Canaveral — launched first, despite the "2" in its name.',
    ],
];
